README.md, docs/requirements.md
It took me a while to realise that the reason it was failing was because I was on 0.9.5. Having this on the front page would be useful.
=> Add a warning that this only works on 0.10

docs/public_methods.md, lua/kulala/init.lua, lua/kulala/ui/selector.lua
Currently the `set_selected_env` API only supports telescope. This changes it to fallback to using native `vim.ui.select`, which can already be mapped to other pickers by using something like [dressing](https://github.com/stevearc/dressing.nvim)
=> Fallback to vim.ui.select if Telescope is not found

lua/kulala/utils/fs.lua
The previous version caused an infinite loop in windows.
Let's pray this one works 🙈.
=> fix(fs-utils): loop until root dir in windows

docs/_coverpage.md, lua/kulala/globals/init.lua, package.json
loading_done icon has now automatically a space after it, when its string length is greater than zero.
=> break: bump version

docs/_coverpage.md, lua/kulala/cmd/init.lua, lua/kulala/config/init.lua, lua/kulala/globals/init.lua, lua/kulala/inlay/init.lua, lua/kulala/parser/init.lua, lua/kulala/ui/init.lua, lua/kulala/utils/fs.lua, package.json
=> make cmd non-blocking

docs/_coverpage.md, lua/kulala/globals/init.lua, lua/kulala/parser/init.lua, package.json
The recent change broke something in my current `.http` calls because we're using a different content-type for json and it was sending out an empty body.
```http
POST http://{{hostname}}/api/users/login/
content-type: application/vnd.api+json
{
"data": {
"type": "User",
"attributes": {
"username": "johndoe",
"password": "sample"
}
}
}
```
I tested this and it solves the issue I was having
=> fix: allow other content types to be used

lua/kulala/parser/graphql.lua, lua/kulala/parser/init.lua
Enable inline graphql support.
This here should work now.. haven't tested mutations, yet, but they should also work..
with variables:
```http
POST https://swapi-graphql.netlify.app/.netlify/functions/index HTTP/1.1
accept: application/json
query Person($id: ID) {
person(personID: $id) {
name
}
}
variables { "id": 1 }
```
without variables:
```http
POST https://swapi-graphql.netlify.app/.netlify/functions/index HTTP/1.1
accept: application/json
query Query {
allFilms {
films {
title
director
releaseDate
speciesConnection {
species {
name
classification
homeworld {
name
}
}
}
}
}
}
```
closes #58
=> feat(parser): add inline graphql support

lua/kulala/globals/init.lua, lua/kulala/parser/init.lua, package.json
The second request previously failed (exit code != 0) because `--data` was set even when body was `nil`. This is due to the newly introduced `DEFAULT_HEADERS`.
```http
POST https://httpbin.org/post HTTP/1.1
{
"username": "{{USERNAME}}",
"password": "{{PASSWORD}}",
"token": "foobar"
}
###
GET https://httpbin.org/get HTTP/1.1
authorization: Bearer {{AUTH_TOKEN}}
```
`http-client.env.json`
```json
{
"_base": {
"DEFAULT_HEADERS": {
"Content-Type": "application/json",
"Accept": "application/json"
}
},
"dev": {
"USERNAME": "gorillamoe",
"PASSWORD": "bananas",
"pokemon": "ditto",
"auth_header": "Authorization: Basic Base64encodedstring=="
},
"prod": {
"USERNAME": "marco",
"PASSWORD": "polo",
"pokemon": "pikachu",
"auth_header": "Authorization: Basic Base64encodedstring=="
}
}
```
This should be …
=> fix(parser): don't set data when body is nil

docs/docs/usage/file-to-variable.md, lua/kulala/globals/init.lua, lua/kulala/parser/init.lua, package.json
Create a file with the `.http` extension and write your JSON request in it.
Then, use the `@file-to-variable` directive to specify the variable name
that you want to use in the request. The second argument is the path to the file.
```http title="file-to-variable.http"
POST https://httpbin.org/post HTTP/1.1
content-type: application/json
accept: application/json
{
"test-include": {{TEST_INCLUDE}}
}
```
The `TEST_INCLUDE` variable will be replaced with the content of the `test-include.json` file.
```json title="test-include.json"
{
"foo": "bar",
"baz": {
"qux": "quux"
}
}
```
This also implements #72.
=> feat(parser): add @file-to-variable meta-tag

lua/kulala/utils/fs.lua
=> fix(fs): avoid infinite loop searching parent dir

lua/kulala/parser/env.lua
Early return inside this for loop is causing the assignment [here](https://github.com/mistweaverco/kulala.nvim/blob/main/lua/kulala/parser/init.lua#L22) to be nil when reading env variables from a `.env` file containing at least one empty line or a comment.
=> fix(env): early return causing nil env table error

docs/docs/usage/public-methods.md, docs/docs/usage/request-variables.md, lua/kulala/cmd/init.lua, lua/kulala/db/init.lua, lua/kulala/external_processing/init.lua, lua/kulala/globals/init.lua, lua/kulala/init.lua, lua/kulala/internal_processing/init.lua, lua/kulala/parser/env.lua, lua/kulala/parser/init.lua, lua/kulala/parser/request_variables.lua, lua/kulala/ui/init.lua, package.json
- Implements named requests
- Removes kulala internal `env` from `vim.env`
- Uses `kulala.db` instead (not messing with environment, which could cause issues)
- Adds `replay()` function (closes #92)
=> feat(parser): named-requests + request-variables + `replay()`

lua/kulala/parser/init.lua
The request line was spliitted by space, so it was not possible to add spaces to the query values.
Now the parts Method, Url, Version are explicitly splitted.
=> Allow spaces in query part from request line

docs/docs/usage/authentication.md, lua/kulala/parser/init.lua
This adds Basic, Digest, NTLM and Negotiate authentication while using the curl arguments.
Readme has been extended and needs proof reading.
=> Basic, Digest, NTLM, Negotiate Auth by Curl

lua/kulala/config/init.lua, lua/kulala/ui/init.lua, lua/kulala/ui/winbar.lua
Adding "tabs" for the result buffer like in lazy.nvim 
To keep the original minimalism, I made this change optional and disabled by default in config, as it is essentially useless 😄
=> feat: add winbar for result buffer

lua/kulala/parser/init.lua
Hi, this is in regards to #121.
With this change, headers are split into key, value pairs at the first colon.
=> fix: split headers into key value at first colon

lua/kulala/config/init.lua, lua/kulala/globals/init.lua, lua/kulala/ui/init.lua
closes: #128.
This also sets the ft to the correct "text" one,
as fallback value for when we don't know the ft.
=> fix(ui): replace buffer when content changes

docs/docs/getting-started/setup-options.md, lua/kulala/config/init.lua, lua/kulala/globals/init.lua, lua/kulala/parser/env.lua, lua/kulala/utils/fs.lua
If enabled, Kulala searches for `.vscode/settings.json` or `*.code-workspace` files in the current directory and its parents to read the `rest-client.environmentVariables` definitions (`$shared` will be treated as `_base`).
If `http-client.env.json` is also present, it will be merged (and overwrites variables from VSCode).
Possible values:
- `true`
- `false`
Default: `false`
Example:
```lua
require("kulala").setup({
vscode_rest_client_environmentvars = true,
})
```
=> Vscode rest client env support

lua/kulala/parser/env.lua
Steps to reproduce:
1. Set a project directory with files:
```ansi
.
├── foo.http
└── http-client.env.json
```
2. Open `foo.http`
3. Try to `require('kulala').run()` any entry.
4. Get a message: `The variable 'VAR_NAME' was not found in the document or in the environment. Returning the string as received ...`
=> hotfix: missing environments from http-client-env-json

lua/kulala/globals/init.lua, lua/kulala/init.lua, lua/kulala/ui/selector.lua
Steps to reproduce:
1. Set a project directory with files:
```ansi
.
├── foo.http
└── http-client.env.json
```
2. Open `foo.http`
3. Run `require('kulala').set_selected_env()`.
4. Nothing happens.
Expected:
Telescope or vim.ui.selector appears to select env.
=> fix: set_selected_env() does nothing

README.md, docs/docs/getting-started/configuration-options.md, docs/docs/getting-started/install.md, docs/docs/usage/dotenv-and-http-client.env.json-support.md, docs/docs/usage/public-methods.md, docs/sidebars.ts
First of all, thank you for such an amazing project! I want to contribute to the README.md file.  
It's usual to have a listing of just a Lua table item as an install snippet. Because many people use a rather structural approach to the configuration of `lazy.nvim`. So, the `require` is already called by them in a separate file.
Also, I removed the `config` because the [official documentation](https://lazy.folke.io/spec#spec-setup) of `lazy.nvim` suggests using `opts` instead of it. It will do the same. It will just call `require('kulala').setup({})` but with less code.
I've tested the change and it works.
=> Update lazy.nvim instruction in README.md

lua/kulala/parser/init.lua
Fixed the issue of Nil pointers in certain URL parsing, such as http://hostname/xxx?a=1&b
=> Fix url parsing bug

docs/docs/usage/authentication.md, lua/kulala/parser/init.lua
Hi:)
I work with AWS quite a lot and would like to use kulala for authenticating requests with [AWS Signature V4](https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html).
I took inspiration from https://github.com/Huachao/vscode-restclient and implemented this feature by parsing the authorization header and using the `--aws-sigv4` curl option.
A request to list all S3 buckets would look like this:
```http
GET https://s3.amazonaws.com/ HTTP/1.1
Authorization: AWS {{AWS_ACCESS_KEY_ID}} {{AWS_SECRET_ACCESS_KEY}} region:us-east-1 service:s3 token:{{AWS_SESSION_TOKEN}}
```
Let me know if you would be interested in merging this:)
=> feat: support AWS-SigV4 authentication

lua/kulala/config/init.lua, lua/kulala/parser/init.lua, lua/kulala/parser/treesitter.lua
Howdy! I hope this sort of PR is welcome.
Thanks for this plugin, i've been using rest.nvim for a while and it's been starting to show it's age. I have a bunch of http snippets that i use frequently and they worked with rest.nvim but were kinda tricky to use with kulala. I eventually figured out that it was because rest.nvim doesn't conform as well to the http file spec, and when i dug in deeper (into the spec and this plugin) I saw an opportunity to clean up some of the manual string parsing you're using with (hopefully) simpler parsing with treesitter.
I don't know if you were hoping to avoid having treesitter as a required dependency so I put this refactor behind an undocumented configuration option to maybe let it bake if you're interested but unsure.
=> parse requests with treesitter

lua/telescope/_extensions/kulala.lua
If telescope is installed, with this change it will be possible to filter the output when using `require('kulala').search()` and `require('kulala').set_selected_env()`
=> feat(telescope): add telescope sorter

lua/kulala/config/init.lua, lua/kulala/parser/init.lua, lua/kulala/parser/inspect.lua, lua/kulala/parser/treesitter.lua, lua/kulala/ui/init.lua, scripts/script.js
follow up to #181
* make `run_all` work with treesitter
* fix graphql requests
* general cleanup
what doesn't work (yet):
* redirecting response bodies to a file, since the `>>` and `>>!` operators aren't part of the http grammar. I opened a [pull request](https://github.com/rest-nvim/tree-sitter-http/pull/40) to add this to the grammar, and have it implemented in my kulala fork in a [separate branch](https://github.com/treywood/kulala.nvim/compare/fix-treesitter-bugs...treywood:kulala.nvim:treesitter-response-redirect)
=> Treesitter Parsing (again)

lua/kulala/parser/init.lua, lua/kulala/ui/init.lua
- fix(ui): remove unused variable
- fix(parser/ui): copy throws an error if no HTTP request is specified
=> fix(ui/parser): remove unused variable, remove nil warnings

lua/kulala/health.lua
Support for neovim health check protocol
https://neovim.io/doc/user/health.html Windows supported too.
`:checkhealth kulala` prints following.
```
==============================================================================
kulala: require("kulala.health").check()
- {kulala.nvim} version 3.7.0
- OK {curl} found
Checking formatters ~
- OK {text/html} formatter: xmllint --format --html -
- WARNING {application/json} formatter not found
- OK {application/xml} formatter: xmllint --format -
```
Inspired by MIT licensed telescope healthcheck
https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/health.lua and https://github.com/folke/lazy.nvim/blob/main/lua/lazy/health.lua
=> feat(checkhealth): support for neovim :checkhealth feature

.github/workflows/tests.yml, .gitignore, scripts/tests.sh, tests/_dockerfiles/ubuntu/Dockerfile, tests/init.vim, tests/minimal_init.lua, tests/minit.lua
Reason: folke and echasnovski both use this.
=> Change testing framework to busted

lua/kulala/parser/init.lua, lua/kulala/parser/treesitter.lua, lua/kulala/ui/init.lua
can merge when https://github.com/rest-nvim/tree-sitter-http/pull/40 is merged and picked up by `nvim-treesitter`
also move all calls to treesitter parsing into the parser module, fix some bugs
=> implement response redirect with treesitter

lua/kulala/lib/shlex/init.lua, tests/lib/shlex/shlex_spec.lua
And more close to Python original. Now it supports like `curl
https://example.com` (without quotes), or ` curl 'https://example.com'`
(with a space at the start).
1. Add a test data from CPython test_shlex.py
2. Reimplement Python code generating a test cases.
3. Mark a few tests as broken and move to separate test case - probably
not worth fixing.
4. Add a fix for curl case - set whitespace_fix to true, this is what
Python shlex.split does.
5. Avoid `goto continue` by introducing a continue boolean flag in a
parsing code. Resulting code is ugly, but it works.
=> fix(shlex): make split function more robust

docs/docs/usage/request-variables.md
Without `Content-Type` header httpbin does not parse request json and as a result `REQUEST_TWO` returns a warning that `{{REQUEST_ONE.response.body.$.json.token}}` is not found.
=> Fix request variables documentation example

lua/kulala/ui/init.lua
When setup
``` lua
vim.opt.foldmethod = 'expr'
vim.opt.foldexpr = 'v:lua.vim.treesitter.foldexpr()'
```
the fold level per lines not getting correct result, this means that `zc` `zo` will not work in result buffer. this commit fix it. 
Related #128
=> fix(ui): treesitter foldexpr calculate not work

lua/kulala/globals/init.lua, lua/kulala/parser/scripts/engines/javascript/init.lua
Close #253 
After a little investigation, I thought it might be due to the value of `script.cwd` being `kulala:` when started with scratchpad.
So I modified it to use the tmp_dir path instead if the value is `kulala:`.
=> fix: resolve "no such file or directory" error in scratchpad

lua/kulala/cmd/init.lua, lua/kulala/globals/init.lua, lua/kulala/internal_processing/init.lua, lua/kulala/parser/init.lua, lua/kulala/parser/utils.lua
- Use headers with casing as supplied in the request (don't lowercase them permanently).
- Also only use last headers from request in content type detection
- Only run post-request scripts if there are any
- make contains utils case-insensitive by default
=> feat(headers): use as supplied + support multiple headers

docs/docs/scripts/request-reference.md, lua/kulala/globals/init.lua, lua/kulala/parser/init.lua, lua/kulala/parser/scripts/engines/javascript/lib/src/lib/PreRequestRequest.ts, lua/kulala/utils/fs.lua
Returns the `string` request body as sent via curl; with variables substituted, or `undefined` if there is no body.
Very useful if you want to see the request body as it was sent to the server.
The `tryGetSubstituted` method will substitute variables with their values, but leave the rest of the body as is.
If you have a GraphQL query in the body, for example, the `getComputed` method will show the query as it was sent to the server, which is quite different from the substituted version.
As an example, if you have a request body like this:
```graphql
query getRestClient($name: String!) {
restclient(name: $name) {
id
name
editorsSupported {
name
}
}
}
{
"variables": {
"name": "{{ENV_VAR_CLIENT_NAME}}"
}
}
```
Then the `getComputed` method will
return the body as it was sent to the server: …
=> feat(scripts): add `request.body.getComputed()`

Makefile, scripts/tag.sh
`make tag` will create a tag based on the version found in `lua/kulala/globals/init.lua` which resembles a string like `v88.84.20091105` and pushes it to the origin remote.
It will fail,
- if the tag already exists
- if you're not on the main branch
- if you're git status is dirty
=> feat(ci): add tag script

lua/kulala/ui/init.lua, tests/test_helper/ui.lua, tests/ui/init_spec.lua
Continuation of #240 
This PR contains tests for:
* from_curl()
* close()
My intention is to continue adding tests, but on different PRs. I tried to avoid having loads of API calls on written on the tests buy using a test helper.
=> test(ui): add tests for from_curl() and close()

lua/kulala/graphql/init.lua
Fixes https://github.com/mistweaverco/kulala.nvim/issues/276
=> fix(graphql): add a Content-Type: application/json if not specified

lua/kulala/ui/init.lua
remove nofile, otherwise ts folds do not work in lazy.
=> fix(ui): folds not working in lazy

docs/docs/getting-started/configuration-options.md, lua/kulala/config/init.lua
I have updated the document to reflect that `stats` can be configured as a view or a winbar pane.
=> docs: add stats to available winbar panes

lua/kulala/parser/treesitter.lua
`require("kulala").inspect()` with `treesitter = true` does not display the body, this PR should address that.
=> fix(treesitter): show body on treesitter inspect

docs/docs/usage/huge-request-body.md, docs/sidebars.ts, lua/kulala/parser/init.lua, lua/kulala/utils/fs.lua
Metatag flag for huge / large request bodies as shown in #299:
```http
POST https://httpbin.org/post HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Accept: application/json
name={{name}}&
age={{age}}
```
this is autmmatically enforce for multipart/form-data content types.
---
Remove assumptions on what is a blob or what is not. This closes #298
=> feat(parser): huge req bodies + don't assume blobs

lua/kulala/internal_processing/init.lua
Solve the problem that the response cannot be formatted when the content-type contains spaces, such as content-type: application/json   ; charset=utf-8
=> fix: space character problem when parsing content-type

lua/kulala/globals/init.lua, lua/kulala/parser/scripts/engines/javascript/init.lua
This is a workaround for a bug/weird behaviour in neovim: https://github.com/neovim/neovim/issues/31107
Once this has been merged:
https://github.com/neovim/neovim/pull/31109
We can revert this workaround.
Fixes #304
=> fix(scripts): windows: js engine build and run

docs/docs/getting-started/configuration-options.md, lua/kulala/config/init.lua, lua/kulala/parser/init.lua, lua/kulala/utils/string.lua
=> Option for encoding query values

lua/kulala/parser/init.lua
After a period of not needing to use kulala, I recently updated it and went to use my saved GraphQL requests. However, I found that none of them were working, because kulala was sending the raw body of the request file, rather than properly parsing it to JSON and sending that blob.
After a bunch of digging, I figured out that bc2eb2d789bf2fe72e1d868c63a522e1c6733edf was the culprit. Specifically, [here](https://github.com/mistweaverco/kulala.nvim/commit/bc2eb2d789bf2fe72e1d868c63a522e1c6733edf#diff-6d98ccc7bb245892121a4c9e28c45f3b507f0610ff34e0ca4d177f84baa71c37L702) and [here](https://github.com/mistweaverco/kulala.nvim/commit/bc2eb2d789bf2fe72e1d868c63a522e1c6733edf#diff-6d98ccc7bb245892121a4c9e28c45f3b507f0610ff34e0ca4d177f84baa71c37L715) changed `gql_json` to `res.body`.
This just …
=> Use the correct body for GraphQL requests

lua/kulala/utils/ascii.lua
Stats panel incorrectly shows `Total Time` units in milliseconds while showing seconds.
Instead of changing the units to seconds. I thought it would be more useful to show all units on the stats page as milliseconds.
Before:
After
=> fix: change units in stats to be millseconds

lua/kulala/parser/init.lua
Adds multline url feature identical to vscode-rest-client:
Every new line starting with
- `?`
- `&`
following the request line is added to the url.
=> Query parameters can be placed in a new line

lua/kulala/cmd/init.lua, lua/kulala/ui/init.lua
Previously the request's `start` timestamp was set before request parsing, which meant that it was started before the user was prompted for any `@prompt` variables.
**The effect was that the duration the user took to submit the prompt was included in the request duration.**
This PR fixes it by updating the `M.open` to mimic what `M.open_all` already does and receive its `start` timestamp from the `CMD.run_parser` callback.
=> fix: don't start request timer until after prompt responses are submitted

lua/kulala/formatter/init.lua, lua/kulala/ui/init.lua
1. When setting a custom formatter, an error will be reported for base_table that does not exist.
```
["text/tsv"] = {
ft = "tsv",
formatter = function(body)
return body:upper()
end,
},
```
2. When using a custom formatter to process the returned buffer, if the autocmd of filetype is set, the first trigger will be an empty buffer.
=> fix(format): fix function format params

docs/docs/usage/api.md, lua/kulala/api/init.lua, lua/kulala/cmd/init.lua, lua/kulala/globals/init.lua
This triggers only once for the next request and
then flushes the queue.
=> feat(api): add `after_next_request`.

lua/kulala/parser/init.lua
This makes something like this possible:
```http
< ./auth.js
POST {{API_URL}} HTTP/1.1
Content-Type: application/json
{{AUTH_HEADER_NAME}}: {{AUTH_HEADER_VALUE}}
```
auth.js
```js
if (request.environment.get("API_ENVIRONMENT") === "local") {
request.variables.set("AUTH_HEADER_NAME", "Context");
request.variables.set("AUTH_HEADER_VALUE", request.environment.get("AUTH_CONTEXT"));
} else {
request.variables.set("AUTH_HEADER_NAME", "AccessToken");
request.variables.set("AUTH_HEADER_VALUE", request.environment.get("AUTH_TOKEN"));
}
```
=> feat(parser): replace variables also in header name

lua/kulala/parser/init.lua, tests/functional/ui_spec.lua
MInor update for #351  to allow `run_allI()` for visual selection.
=> Fix: to allow run_all() for visually selected lines (#325)

lua/kulala/config/init.lua, lua/kulala/config/keymaps.lua, lua/kulala/ui/init.lua, lua/kulala/ui/winbar.lua, tests/functional/ui_spec.lua, tests/test_helper/ui.lua
1. Added default keymaps: global, filetype, local and initialization logic to enable/disable/customize keymaps.
2. Added two config options: 
- `global_keymaps = false` by default - will enable/disable/customize default keymaps globally and for http/rest filetypes.
-  `kulala_keymaps = true` by default - will enable/disable/customize default keymaps for Kulala UI.
=> Add default keymaps

lua/kulala/cmd/init.lua, lua/kulala/config/init.lua
Resolves #368 
Problem:
- a regression introduced in #346 when removing `vim.fn.jobstart` in favour of `vim.system`.   Single requests when run with `vim.system` are queued with `wait()`.
Fix: 
- Skip `wait()` for single requests.
Change:
- added config option `request_timeout = nil` by default, to set max timeout.
=> Fix: Send one-off request async (#368)

lua/kulala/config/keymaps.lua
Hello!
With the introduction of `[` and `]` as means to navigate the request history, one thing that's bugging me out is the delay. Since there are default mappings that start with `[` and `]` (`[[` and `]]` respectfully), neovim waits `'timeoutlen'` for another key before executing the initial action.
To handle that, we can just make all mappings use the `nowait` option. From my testing, this does not interfere with any other default keymaps.
=> fix: use nowait for keymaps

README.md, docs/docs/getting-started/configuration-options.md, docs/docs/getting-started/install.md, docs/docs/usage/api.md, lua/kulala/cmd/init.lua, lua/kulala/config/init.lua, lua/kulala/parser/document.lua
- update docs: API
- update readme: install section
- update docs: config options
- update config: replace `FS.command` with `vim.fs.executable`
- minor fix: document parser: strip comment chars only for non-http files
=> Fix: update docs for API hooks

lua/kulala/ui/init.lua
`nvim_win_get_width` and `nvim_win_get_height` returns the size of the current window, so if we have many windows in 1 tab, the opening float would be really small. I think we should use size of the screen instead
=> fix: use screen size instead of win size for float

lua/kulala/cmd/init.lua, lua/kulala/parser/document.lua, lua/kulala/parser/request.lua, lua/kulala/utils/table.lua, scripts/tests.sh, tests/functional/parser_spec.lua, tests/functional/ui_spec.lua
- Fix: allow # and // comment chars on non-first char line position. Closes #410 
- Fix: disable repeated request processing when replaying.  Closes #415
=> Fix(parser): replay and comments

lua/kulala/parser/request.lua, scripts/tests.sh, tests/functional/requests_spec.lua
=> Feat: add GRAPHQL method support

docs/docs/usage/import-and-run-http.md, docs/sidebars.ts, lua/kulala/cmd/init.lua, lua/kulala/parser/document.lua, lua/kulala/parser/request.lua, lua/kulala/utils/complete.lua, lua/kulala/utils/table.lua, tests/functional/parser_spec.lua, tests/functional/requests/advanced_A.http
Feat: add import and run commands (IntelliJ Comp)
- `import *.http` command
- `run *.http` - to run the whole http file
- `run #Request name` - to run a specific request from imported file
- `<C-x> <C-u>` - to autocomplete imported request names
=> Feat: add import and run commands

lua/kulala/inlay/init.lua
Virtual text when used with `cursorline` overrides the BG color of the cursorline, using `hl_mode = "combine"` makes it so they blend together.
Before:
After:
=> feat(virt_text): use 'combine' to blend with cursorline

lua/kulala/parser/document.lua, tests/functional/parser_spec.lua
Support for:
```http
GET http://example.com:8080
/api
/html
/get
?id=123
&value=content
```
=> Feat: add support for multiline URLs

lua/kulala/ui/winbar.lua
Old:
New:
It is hard to read which tab is activated with the current winbar.
This PR aims to fix that by making the shortcut key part of the tab highlight.
=> fix: fix winbar highlights

README.md, lua/kulala/config/defaults.lua, lua/kulala/config/keymaps.lua, tests/functional/keymaps_spec.lua
This pull request introduces a new globalKeymapPrefix configuration option.
Previously, the global keymap could unintentionally override user-defined keymaps.
By setting a custom prefix, users can now prevent conflicts and better integrate with their own configurations.
=> Add `global_keymaps_prefix` option to prevent overriding user keymaps

doc/kulala.http-file-spec.txt, docs/docs/usage/http-file-spec.md
I added a few words to the docs making clear that this is supported out of the box.
=> docs: Add note about url encoding (#500)

lua/kulala/parser/env.lua
Fixes issue where `Json.parse(settings_json_content)` returns nil by using `FS.read_json` instead.
- Removed unused `Json` module
- Switched to `FS.read_json` for reading VSCode settings files
- Simplified file reading logic
The current implementation using `Json.parse` was returning nil, causing VSCode settings to not be properly loaded. Using `FS.read_json` resolves this issue.
=> refactor: use FS.read_json for VSCode settings and remove unused Json module

lua/kulala/parser/env.lua
Originally, I couldn't load the VSCode settings environment when I opened Telescope by calling  `set_selected_env()`.
I found out that:
```lua
local success, settings_json_content = pcall(vim.fn.readfile, vscode_dir .. "/settings.json")
```
`settings_json_content` is actually a table, but
```lua
local settings = Json.parse(settings_json_content)
```
`Json.parse` requires a string.
After I concatenated all the lines in `settings_json_content`, I was able to load the VSCode settings correctly.
=> fix(parser): vscode settings parse

lua/kulala/parser/document.lua, lua/kulala/parser/request.lua, tests/functional/oauth_spec.lua, tests/functional/parser_spec.lua
This PR adds support for using variables in redirect responses file name.
Previously, redirect responses were limited to static filename. This limitation made it difficult to support workflows that require passing dynamic values (e.g., redirecting to a page based on a query or command argument).
```http
###
@page=5
GET {{ENDPOINT_URL}}/items?start={{page}}&limit=25
Content-Type: application/json
Accept: application/json
>> institutions_{{page}}.json
```
=> feat: allow using variables in redirect response

lua/kulala/ui/winbar.lua, tests/functional/ui_spec.lua
This PR adds mouse support for the winbar headers, so clicking on each item will navigate us there.
I dont have much experience contributing, so let me know if anything needs to be changed or removed.
Preview:
https://github.com/user-attachments/assets/d326eecd-2104-49a7-bdfd-ed2ab150667b
=> feat: Mouse support for winbar ui

lua/kulala/graphql/init.lua, tests/functional/requests_spec.lua
Hi, first time contributing. Let me know if there is anything that needs refining. 
Currently, graphql introspection does not add cookies to the introspection request.
Therefore, it fails if there is a need for authentication. 
This MR adds the cookies under the `--cookie` flag to the request.
=> Add cookies to graphql introspection request
