mistweaverco/kulala.nvim

- lua/kulala/config/init.lua
- lua/kulala/inlay/init.lua
- lua/lualine/components/kulala.lua
Adds the ability to change icons ('⏳', '✅ ', '🐼') to other icons or text.
> Icons config

- README.md
- docs/_coverpage.md
- docs/install.md
- lua/kulala/config/init.lua
- lua/kulala/globals/init.lua
- lua/kulala/parser/init.lua
- package.json
> feat: add custom additional curl opts

- lua/kulala/config/init.lua
- lua/kulala/formatter/init.lua
- lua/kulala/init.lua
- lua/kulala/inlay/init.lua
- lua/kulala/parser/dynamic_vars.lua
- lua/kulala/parser/init.lua
- lua/kulala/ui/init.lua
- lua/lualine/components/kulala.lua
> fix: config-reset

- docs/docs/usage/dotenv-and-http-client.env.json-support.md
- lua/kulala/globals/init.lua
- lua/kulala/parser/env.lua
- lua/kulala/parser/init.lua
- lua/kulala/ui/selector.lua
- lua/telescope/_extensions/kulala.lua
- package.json
> feat(env): add DEFAULT_HEADERS

- docs/docs/public_methods.md
- lua/kulala/globals/init.lua
- lua/kulala/init.lua
- lua/kulala/ui/init.lua
- package.json
Copies the current request as cURL to the clipboard.
This closes #67.
> feat: add `.copy()` function

- docs/docs/http_file_spec.md
- docs/docs/usage/graphql.md
- docs/docs/usage/magic-variables.md
- docs/docs/usage/sending-form-data.md
- docs/docs/usage/using-environment-variables.md
- docs/docs/usage/using-variables.md
- lua/kulala/parser/init.lua
> chore(docs): update to match kulala-fmt

- docs/docs/public_methods.md
- lua/kulala/globals/init.lua
- lua/kulala/init.lua
- lua/kulala/ui/init.lua
- package.json
> feat(ui): add `close()` function

- README.md
The links in the README did not point to the corret location in the docs page
> fix(docs): fix README links to docs

- lua/kulala/parser/dynamic_vars.lua
- lua/kulala/utils/fs.lua
https://luals.github.io/wiki/annotations/#return
> docs: fix type annotations syntax to follow LuaCATS

- docs/docs/usage/dynamically-setting-environment-variables-based-on-headers.md
- docs/docs/usage/dynamically-setting-environment-variables-based-on-response-json.md
- docs/sidebars.ts
- lua/kulala/cmd/init.lua
- lua/kulala/globals/init.lua
- lua/kulala/internal_processing/init.lua
- package.json
> feat(parser): add env-header-key meta tag

- lua/kulala/globals/init.lua
- lua/kulala/utils/fs.lua
- package.json
Fix regression. This closes #88.
> fix(fs): find nearest file

- docs/docs/usage/public-methods.md
- lua/kulala/init.lua
- lua/kulala/ui/selector.lua
- lua/kulala/utils/fs.lua
- lua/telescope/_extensions/kulala.lua
> feat: add search()

- docs/docs/getting-started/setup-options.md
- docs/docs/usage/automatic-response-formatting.md
- docs/docs/usage/dotenv-and-http-client.env.json-support.md
- docs/docs/usage/public-methods.md
- docs/docs/usage/request-variables.md
- lua/kulala/config/init.lua
- lua/kulala/globals/init.lua
- lua/kulala/init.lua
- lua/kulala/ui/init.lua
> feat(ui): add scratchpad

- docs/docs/getting-started/setup-options.md
> docs: add winbar option

- lua/kulala/ui/winbar.lua
Incorrect comment, that needs to be removed.
> chore: remove incorrect comment

- lua/kulala/parser/request_variables.lua
> fix(parser): req-vars array access

- lua/kulala/parser/init.lua
Refactored authorization header parsing to fix error from issue #118.
Closes #118
> Refactor authorization header parsing

- docs/docs/getting-started/setup-options.md
- lua/kulala/config/init.lua
- lua/kulala/ui/init.lua
Here is a screenshot of the result:
> Add the option to show both headers and body

- docs/docs/getting-started/setup-options.md
> Docs: fix content_types -> contenttypes

- docs/docs/getting-started/setup-options.md
- lua/kulala/config/init.lua
Also update default scratchpad contents
> chore(docs): update setup-options.md

- lua/kulala/globals/init.lua
- lua/kulala/ui/callbacks.lua
- lua/kulala/ui/init.lua
- lua/kulala/ui/winbar.lua
> fix(winbar): keymappings not working anymore

- lua/kulala/globals/init.lua
- lua/kulala/ui/init.lua
- lua/kulala/ui/winbar.lua
> fix: winbar + default_view

- lua/kulala/scripts/javascript.lua
> feat(scripts): print output

- docs/docs/usage/redirect-the-response.md
- docs/sidebars.ts
- lua/kulala/cmd/init.lua
- lua/kulala/internal_processing/init.lua
- lua/kulala/parser/init.lua
- lua/kulala/utils/fs.lua
> feat(redir-response)

- .editorconfig
- stylua.toml
Avoid affecting pr due to different local formatting configurations.
> Standardize the code format

- lua/kulala/parser/init.lua
> feat(req-blocks): optional comments

- lua/kulala/parser/treesitter.lua
fix #223 for people with out-of-date parsers not using treesitter parsing
> lazily parse treesitter queries

- docs/docs/getting-started/configuration-options.md
- docs/docs/usage/authentication.md
- lua/kulala/config/init.lua
- lua/kulala/parser/init.lua
> SSL Client Certificate Auth

- docs/docs/usage/sending-form-data.md
- lua/kulala/parser/init.lua
- lua/kulala/parser/inspect.lua
- lua/kulala/utils/fs.lua
Form-data is now handled correctly.
Also added the possiblity to add and send binary files in form-data.
Added body_display which is basically a body that is meant to be displayed in some way (for now it's only stripped from binary data).
> fix(parser): form-data + binary

- lua/kulala/ui/init.lua
> Keep alternative-file

- docs/docs/getting-started/configuration-options.md
- lua/kulala/config/init.lua
- lua/kulala/ui/init.lua
> feat(display_mode): split or float

- lua/kulala/parser/inspect.lua
Fixes #327
(also refactors the way to add a space to not modify the req table content)
> Added missing HTTP/ prefix to Inspect output

- docs/docs/getting-started/configuration-options.md
- lua/kulala/config/init.lua
- lua/kulala/ui/init.lua
> feat(float): add `q_to_close_float` config option

- lua/kulala/cmd/init.lua
> fix(cmd): loading icon not shown

- lua/kulala/cmd/init.lua
This is a follow up for #368 to allow async for `run_all()` requests.
> Fix: allow async for run_all() (#368)

- .gitignore
Feature:
- Store responses history during a Neovim session
- Allow to scroll backwards and forward through responses
> Feat: add request/response history

- lua/kulala/inlay/init.lua
- lua/kulala/ui/init.lua
- tests/functional/requests_spec.lua
Fix: do not reopen kulala win in another tab.
Resolves #379
> Fix: do not reopen kulala win in another tab

- lua/kulala/api/init.lua
- lua/kulala/cmd/init.lua
- lua/kulala/config/init.lua
- lua/kulala/ui/init.lua
- tests/functional/requests_spec.lua
- tests/functional/ui_spec.lua
Feature: Add custom response handler - Closes #326 
- modified config option `default_view = body|headers|headers_body|verbose|function(response) .. end`, which can contain custom logic to display/process response.
> Feat: Custom response handler

- lua/kulala/parser/document.lua
seems to be a regression. this fixes it.
> fix(parser): redirect response with overwrite enabled

- docs/docs/usage/http-file-spec.md
- lua/kulala/inlay/init.lua
- lua/kulala/parser/curl.lua
- lua/kulala/parser/document.lua
- lua/kulala/parser/request.lua
- lua/kulala/parser/utils.lua
- lua/kulala/ui/init.lua
- lua/kulala/utils/string.lua
- tests/functional/grpc_spec.lua
- tests/functional/parser_spec.lua
- tests/functional/requests_spec.lua
- tests/functional/ui_spec.lua
- tests/parser/curl_spec.lua
- add support for `Cookie:` header.  Resolves #393 
- fix handling of empty lines.  Resolves #389
> Feat: Cookie: header support

- lua/kulala/parser/document.lua
> Fix(parser): correctly handle empty lines

- lua/kulala/health.lua
- lua/kulala/parser/request.lua
- tests/functional/fixtures/simple.json
- tests/functional/parser_spec.lua
- add support for variables in external `json` files
- add gRPCurl check to checkhealth
> Feat: replace vars in external json

- docs/docs/usage/api.md
- lua/kulala/parser/scripts/engines/javascript/init.lua
- lua/kulala/utils/fs.lua
- tests/functional/ui_spec.lua
Update FS.get_path expand functions to ignore `wildignore` setting.
Closes #411
> FIX: Js update fix

- docs/docs/getting-started/configuration-options.md
- lua/kulala/config/init.lua
- lua/kulala/ui/init.lua
Add an option to override default UI window settings. 
Closes #409
> Feat: add win_opts config option

- NEWS.md
- lua/kulala/config/init.lua
- lua/kulala/config/keymaps.lua
- lua/kulala/ui/float.lua
- lua/kulala/ui/init.lua
- lua/kulala/ui/report.lua
- lua/kulala/ui/utils.lua
- lua/kulala/utils/fs.lua
Feat: add news hint, that shows up on version change
> Feat: add news hint

- docs/docs/usage/websockets.md
- docs/sidebars.ts
- lua/kulala/cmd/init.lua
- lua/kulala/cmd/websocket.lua
- lua/kulala/config/init.lua
- lua/kulala/config/keymaps.lua
- lua/kulala/health.lua
- lua/kulala/logger/init.lua
- lua/kulala/ui/init.lua
- tests/functional/websockets_spec.lua
- tests/test_helper/stubs.lua
- tests/test_helper/ui.lua
Feat: Websockets support
- uses `websocat` under the hood - https://github.com/vi/websocat
- run `WS wss://echo.websocket.org/`
- `<CR>` - to send message, `<C-c>` - to close connection
> Feat: Websockets support

- lua/kulala/config/init.lua
> Fix(ui): do not set signs if signcolumn not used

- lua/kulala/parser/document.lua
- lua/kulala/parser/request.lua
- lua/kulala/ui/init.lua
- tests/functional/parser_spec.lua
Feat: meet IntelliJ spec for url line
- Full spec: absolute/origin/asterisk paths support
> Feat: URL line - comply with IntelliJ spec

- lua/kulala/ui/winbar.lua
> Fix: winbar keymaps init

- .gitignore
- .log.lua
- NEWS.md
- docs/docs/scripts/lua-scripts.md
- docs/docs/scripts/request-reference.md
- docs/docs/usage/request-variables.md
- docs/static/import/demos/5.script.http
- lua/kulala/cmd/lsp.lua
- lua/kulala/parser/document.lua
- lua/kulala/parser/jsonpath.lua
- lua/kulala/parser/request.lua
- lua/kulala/parser/scripts/engines/javascript/lib/package.json
- lua/kulala/parser/scripts/engines/javascript/lib/src/lib/PostRequest.ts
- lua/kulala/parser/scripts/engines/javascript/lib/src/lib/PreRequestRequest.ts
- lua/kulala/parser/scripts/init.lua
- lua/kulala/parser/scripts/lua/init.lua
- tests/functional/fixtures/request_2_errors_payload.txt
- tests/functional/parser_spec.lua
* feat(scripting): add request.iteration() - current count of request
* fix(parser): jsonpath resolver
* fix(parser): remove trailing \n from the end of the body
> feat(scripting): add request.iteration() - current count of replays

- .log.lua
- lua/kulala/cmd/lsp.lua
- lua/kulala/parser/graphql.lua
- lua/kulala/parser/request.lua
- lua/kulala/utils/json.lua
- tests/functional/requests_spec.lua
* fix(parser): allow GRAPHQL method
* fix(lsp): skip requests with no name
> fix(parser): allow GRAPHQL method
